### PR TITLE
refactor: optimize the attached events visualization in the trace widget

### PR DESCRIPTION
**Pull request by Fine0830**
Optimize the attached events visualization in the trace widget.

Video 

https://user-images.githubusercontent.com/20871783/218655833-dbb82736-d3d6-4b28-a4dd-b522caecd2cf.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by mrproliu** [comment]
This looks great. I have two suggestions:
1. Can we change the time view on the right to match the view in the trace, so that users can easily see the start and end times of events and understand the relationships between events?
2. The order of the events should be sorted by ascending.

**Comment by Fine0830** [comment]
> This looks great. I have two suggestions:
> 
> 1. Can we change the time view on the right to match the view in the trace, so that users can easily see the start and end times of events and understand the relationships between events?

Do you mean to move parts of the whole events to the trace view?

**Comment by wu-sheng** [comment]
I think he means use that style, rather han moving in to trace page.
The key is showing the duration with order.

**Comment by mrproliu** [comment]
I think he means use that style, rather han moving in to trace page.

> Yes.

**Comment by Fine0830** [comment]
Trace graph? The events data is not a tree structure.

**Comment by mrproliu** [comment]
> Trace graph? 

We only need the style on the right side of the trace.

> The events data is not a tree structure.

Yes, the events are only a list. we only need the start/end time and duration, so it doesn't matter if the events are tree or list structure.

**Comment by wu-sheng** [comment]
Yes, the right part of trace view only.

**Pull request closed without merging**
