### PR TITLE
add a netty icon

### PR DESCRIPTION
**Pull request by peachisai**
image

### CODE REVIEW

**Review by Fine0830 — DISMISSED** [review]

**Comment by wu-sheng** [comment]
This should be netty-http.

**Comment by peachisai** [comment]
> This should be netty-http.

Is it okay for all the Netty traces to use the same icon? Or should it be renamed to "netty-http"?

**Comment by wu-sheng** [comment]
> > This should be netty-http.
> 
> Is it okay for all the Netty traces to use the same icon? Or should it be renamed to "netty-http"?

It follows the ID you add through https://github.com/apache/skywalking/pull/11442. So, it has to be netty-http

**Comment by wu-sheng** [comment]
And the file name should be all in upper case.

**Comment by wu-sheng** [comment]
> And the file name should be all in upper case.

You missed this, and please compress the icon. 26k is too large. We are expecting the size < 5k.

**Comment by wu-sheng** [comment]
You forget the renaming. :P

**Comment by peachisai** [comment]
> You forget the renaming. :P
Okay

**Comment by peachisai** [comment]
> You forget the renaming. :P

Okay

**Comment by wu-sheng** [comment]
Could you double-check locally? Is `-` going to be removed automatically and request the `NETTYHTTP.png` by the UI?

**Comment by peachisai** [comment]
> Could you double-check locally? Is `-` going to be removed automatically and request the `NETTYHTTP.png` by the UI?

image

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
