### PR TITLE
Add websockets icon

### PR DESCRIPTION
**Pull request by Superskyyy**
For Python agent plugin

### CODE REVIEW

**Comment by Superskyyy** [comment]
Waiting for agent side PR

**Comment by wu-sheng** [comment]
23k icon seems too large, could you try to compress it to ~10k?

**Comment by Superskyyy** [comment]
Sure I'll do that later. Btw is this icon too wide?

**Comment by Superskyyy** [comment]
I compressed it to 12k

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
