### PR TITLE
Add impala icon 4 impala jdbc plugin

### PR DESCRIPTION
**Pull request by lv-lifeng**

### CODE REVIEW

**Comment by wu-sheng** [comment]
25k is too large for an icon on topology. Please refer to other icon size, and compress or adjust icon size.

**Comment by lv-lifeng** [comment]
> 25k is too large for an icon on topology. Please refer to other icon size, and compress or adjust icon size.

ok :-)

**Comment by lv-lifeng** [comment]
compressed to 5k, is it ok

**Comment by wu-sheng** [comment]
Haven't you tested? This icon name seems not right.

**Comment by lv-lifeng** [comment]
I haven't tested it indeed. It's OK now :-)

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
