### PR TITLE
feat: add mq menu

### PR DESCRIPTION
**Pull request by innerpeacez**
image

### CODE REVIEW

**Comment by innerpeacez** [comment]
The icon was given to me by ChatGPT. If it's not good enough, it can be modified again.

**Review by Fine0830 — DISMISSED** [review]

**Comment by wu-sheng** [comment]
Redis is a database rather than a cache from Redis official perspective. 
Do you have others to add?

**Comment by innerpeacez** [comment]
> Redis is a database rather than a cache from Redis official perspective.
Do you have others to add?

Not at the moment, I just made some quick changes. I will roll it back.

**Comment by wu-sheng** [comment]
> > The queue icon seems strange. We need a new one, and also we should have the ownership(new rather than a copy) for License perspective.
> 
> 
> 
> For the icon, I don't have any specific idea. Can you provide an SVG file for me?

@Fine0830 Could you build one?

**Comment by Fine0830** [comment]
> > > The queue icon seems strange. We need a new one, and also we should have the ownership(new rather than a copy) for License perspective.
> > 
> > 
> > For the icon, I don't have any specific idea. Can you provide an SVG file for me?
> 
> @Fine0830 Could you build one?

Sure.

**Comment by innerpeacez** [comment]
> > > > The queue icon seems strange. We need a new one, and also we should have the ownership(new rather than a copy) for License perspective.
> > > 
> > > 
> > > For the icon, I don't have any specific idea. Can you provide an SVG file for me?
> > 
> > 
> > @Fine0830 Could you build one?
> 
> Sure.

thx.

**Comment by Fine0830** [comment]
WDYT @wu-sheng @innerpeacez

**Comment by wu-sheng** [comment]
Work for me.
Is this PR ready to merge? @innerpeacez

**Comment by innerpeacez** [comment]
> WDYT @wu-sheng @innerpeacez
> 
> 

Nice.

**Comment by innerpeacez** [comment]
> Is this PR ready to merge? @innerpeacez

I think it's ok

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
