### PR TITLE
Update i18n for rocketmq monitoring

### PR DESCRIPTION
**Pull request by peachisai**
refer to https://github.com/apache/skywalking/pull/11758

### CODE REVIEW

**Comment by wu-sheng** [comment]
Hold until https://github.com/apache/skywalking/pull/11758 gets approval.

**Comment by peachisai** [comment]
@wu-sheng  
Hello, Should this be mentioned?

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
@peachisai I think this is only about translation. The UI should work without this, right?

**Comment by peachisai** [comment]
> Update i18n for rocketmq monitoring

Yes,I just remenber it

**Comment by wu-sheng** [comment]
You could sync the UI submodule.

**Pull request merged**
