### PR TITLE
Fix/trace duration filters

### PR DESCRIPTION
**Pull request by pemeraldy**
1. Carried out a fix on the Filter component for `minTraceDuration `and `maxTraceDurarion ` filter values that were not working on trace search.
https://github.com/apache/skywalking-booster-ui/blob/7e0d716111cd09f976195435a48fcca9141d2816/src/views/dashboard/related/trace/Filter.vue#L177
https://github.com/apache/skywalking-booster-ui/blob/7e0d716111cd09f976195435a48fcca9141d2816/src/views/dashboard/related/trace/Filter.vue#L178

### CODE REVIEW

**Comment by wu-sheng** [comment]
Are you going to fix this through another PR? Is there a bug?

**Comment by BFergerson** [comment]
@pemeraldy, you can't push all your changes. You need to specifically pull out the bug fix.

**Comment by pemeraldy** [comment]
> Are you going to fix this through another PR? Is there a bug?

Yes that is what I am to do

**Comment by pemeraldy** [comment]
> @pemeraldy, you can't push all your changes. You need to specifically pull out the bug fix.

Yes, that is why I closed it. So I can open another without other changes

**Comment by wu-sheng** [comment]
Please check the latest, I think @Fine0830 fixed this yesterday after you closed this.

**Comment by pemeraldy** [comment]
Oh, that's ok.

**Comment by wu-sheng** [comment]
Welcome to the community, feel free to submit a new when you find another one.

**Comment by pemeraldy** [comment]
Thanks @wu-sheng. Yeah, sure.

**Pull request closed without merging**
