### PR TITLE
feat: set a url parameter to activate tab index

### PR DESCRIPTION
**Pull request by Fine0830**
Closes https://github.com/apache/skywalking/issues/9184

Video 

https://user-images.githubusercontent.com/20871783/173530442-5e7143ac-6255-4fb5-afc2-2f7a6ee406a4.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is this working for two tabs on one page or nested tab components? We are not using in this way, but it is better we could be clear about what would happen if do so.

**Comment by wu-sheng** [comment]
In multiple tabs, how this `/tab/{index}` works? Could you share an example?

**Comment by Fine0830** [comment]
> In multiple tabs, how this `/tab/{index}` works? Could you share an example?

**Comment by Fine0830** [comment]
> So, we can't set index=0 to tab1 and index=1 to tab2, right?

Right.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
