### PR TITLE
feat: support the process dashboard and create the time range text widget

### PR DESCRIPTION
**Pull request by Fine0830**
Support the process dashboard and create the time range text widget.

Video 

https://user-images.githubusercontent.com/20871783/184570573-55ba9e5b-e960-4e91-a75f-7c3021034360.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you add a text field as additional description?

**Comment by Fine0830** [comment]
> Could you add a text field as additional description?

What do you think of this?

https://user-images.githubusercontent.com/20871783/184588565-9b55029c-0307-44f3-bc00-3d4edb1af7ce.mov

**Comment by wu-sheng** [comment]
Let us put the text before the time range.

**Comment by Fine0830** [comment]
Screenshot

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
