### PR TITLE
Add Nacos icon

### PR DESCRIPTION
**Pull request by peachisai**
Add Nacos icon

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you share the screenshot of topology? I want to confirm how this looks like on the topo.

**Comment by peachisai** [comment]
> 

i'm puzzled why its type is unkown
image
i replace springMvc icon,it properly show as follow if it works on right
image

**Comment by peachisai** [comment]
> @peachisai Any update?

i am puzzled with it show unknow type in topo
image

i replace springMvc icon,if it works on right it will show as follow
image

**Comment by wu-sheng** [comment]
Why it is named `oap-service`? Did you install the agent on the OAP server? Or just a name.

**Comment by peachisai** [comment]
> file

just a name

**Comment by peachisai** [comment]
> Why it is named `oap-service`? Did you install the agent on the OAP server? Or just a name.

just a name

**Comment by peachisai** [comment]
@wu-sheng 
May i ask a question ?
I add the component and put the mapping
image

image

image
image

But it still does not show the nacos icon,Should I do something else?

**Comment by wu-sheng** [comment]
That is strange. I didn't know why this happens. I think you need to check why this happens.
We need to check the data in the database, is the component field having the right value?

**Comment by peachisai** [comment]
> That is strange. I didn't know why this happens. I think you need to check why this happens. We need to check the data in the database, is the component field having the right value?

ok,i will solve it

**Comment by wu-sheng** [comment]
`ServiceTopologyBuilder` and `RPCAnalysisListener` should be the key part to locate the root issues.

**Comment by peachisai** [comment]
> `ServiceTopologyBuilder` and `RPCAnalysisListener` should be the key part to locate the root issues.

It helps a lot.I found all the component field is correct .But the nacos server in topo is a real node which can be directly detected .so it will not set the server name.
(W72S{75KLB_Z2KW 9$POA
And it seems icon names should not contain '-' sympol, i remove it and the icon will display
 
image

**Comment by wu-sheng** [comment]
Thanks for the update, and debug so detailedly. According to this, we don't need the logo anymore, as it can't be shown up. And we don't need to rename the ID 150. Could you revert the PR of the plugin?

**Comment by peachisai** [comment]
> Thanks for the update, and debug so detailedly. According to this, we don't need the logo anymore, as it can't be shown up. And we don't need to rename the ID 150. Could you revert the PR of the plugin?

ok ,i will

**Pull request closed without merging**
