### PR TITLE
Add AWS menu for supporting AWS monitoring

### PR DESCRIPTION
**Pull request by pg-yang**
Relation issue: https://github.com/apache/skywalking/issues/9883
There are two things need to confirm :
1.  I didn't find an appropriate icon. 
     Could we use official icon? If we could do this, I think the style of official icon is different with our UI
3. Is the order of the menu appropriate?

image

### CODE REVIEW

**Review by Fine0830 — COMMENTED** [review]
Please add texts for menus title in the `src/locales/lang/xx.ts`

**Comment by Fine0830** [comment]
> Could we use official icon?

Sure, please feel free to change this.

**Comment by wu-sheng** [comment]
> Could we use official icon?

We should not use AWS logo, we are not granted. And please add AWS Cloud as level one, just after `infra` menu.

**Comment by wu-sheng** [comment]
We should put all AWS service into one catalog, as it is a cloud vendor version. Right now, we would not show it on the showcase. But we should consider another aws-showcase project for those. @pg-yang @kezhenxu94  WDYT?

**Comment by wu-sheng** [comment]
> > We should put all AWS service into one catalog, as it is a cloud vendor version. Right now, we would not show it on the showcase. But we should consider another aws-showcase project for those. @pg-yang @kezhenxu94 WDYT?
> 
> Do you mean another GitHub repository outside of apache?

It doesn't have to be out of ASF, I think. Any license relative issue? I just don't want to make the showcase too complex.

**Comment by kezhenxu94** [comment]
> > > We should put all AWS service into one catalog, as it is a cloud vendor version. Right now, we would not show it on the showcase. But we should consider another aws-showcase project for those. @pg-yang @kezhenxu94 WDYT?
> > 
> > 
> > Do you mean another GitHub repository outside of apache?
> 
> It doesn't have to be out of ASF, I think. Any license relative issue?

Yes I think so too, there should be no license issue.

> I just don't want to make the showcase too complex.

Creating a new repo is ok to me, but it might bring some duplication of codes, and if users want to set up all features including AWS ones, they might have some trouble to set up the 2 projects, this might also happen in our demo (if we want to add them to our demo)

**Comment by wu-sheng** [comment]
> Creating a new repo is ok to me, but it might bring some duplication of codes, and if users want to set up all features including AWS ones, they might have some trouble to set up the 2 projects, this might also happen in our demo (if we want to add them to our demo)

I am thinking about this two. But right now, our demo is running on GCP, do you have any idea to also support AWS deployment?

**Comment by wu-sheng** [comment]
Then we have to move it to EKS deployment. This doesn't help our demo env, only available on showcase.
Also, we could have more cloud vendor monitoring, GCP, Azure, even Aliyun.

**Comment by kezhenxu94** [comment]
> Then we have to move it to EKS deployment. This doesn't help our demo env, only available on showcase.

I don't plan to move it to EKS. Adding an optional feature to create EKS is for convenient setup/verify and demonstration of the vendor monitoring. 

> Also, we could have more cloud vendor monitoring, GCP, Azure, even Aliyun.

In those cases, we will also have optional steps to create GKE, Azure Kubernetes cluster, and AliCloud Kubernetes cluster.

In my opinion, we are not going to demonstrate cross-vendor features (i.e. Google and AWS at the same time), so we can add AWS-related monitoring feature in showcase but deploy demo.apache.org in GKE. Think in this way, we will be able to monitor all vendors' services, but at a time, we can only deploy the showcase in one vendor, and in our demo we say we are demonstrating the Google ones but users can still choose to deploy the showcase in their interesting cloud vendor.

**Comment by wu-sheng** [comment]
@pg-yang Let's see how many things we need to add into current showcase, then we could make the decision. I am concerned about with more AWS service + CloudWatch setup, we need some scripts to open service accordingly.

**Comment by wu-sheng** [comment]
I think this PR should be good to continuous. @pg-yang

**Comment by pg-yang** [comment]
> we need some scripts to open service accordingly.

Got, These scripts should be written to showcase project, and user could deploy showcase to EKS (or other cloud service), The ideal way is that users only need to configure access-token of AWS. Right ?


> I think this PR should be good to continuous

I will fix the issues proposed by Fine0830 tonight

**Comment by kezhenxu94** [comment]
> > we need some scripts to open service accordingly.
> 
> Got, These scripts should be written to showcase project, and user could deploy showcase to EKS (or other cloud service), The ideal way is that users only need to configure access-token of AWS. Right ?
> 

I don't recommend to use raw shell scripts to create AWS resources, one way I prefer is to use [Terraform](https://www.terraform.io) to create those resources, users only need to provide access key / access secret and run our showcase command such as `make deploy.kubernetes FEATURE_FLAGS=aws,<others>`

**Comment by wu-sheng** [comment]
Yes, Terraform is better for cloud service deployment.

**Comment by pg-yang** [comment]
@Fine0830 The lang has changed

image

image

image

**Comment by wu-sheng** [comment]
Could you move AWS to level one? I don't want this so deeply menu.

Infra is about general stack, AWS is a specific vendor.

**Comment by pg-yang** [comment]
> Could you move AWS to level one?

AWS Cloud is level one for now. The lack of icon makes it looks like level two.

**Comment by wu-sheng** [comment]
@Fine0830 Could you create a logo for this cloud vendor?

**Pull request merged**
