### PR TITLE
feat: add PostgreSQL to Database sub-menu 

### PR DESCRIPTION
**Pull request by Fine0830**
According to https://github.com/apache/skywalking/pull/9495#discussion_r951057489, add PostgreSQL to Database sub-menu.

Screenshot

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
@yswdqz You should be able to follow this and add a menu on your own next time :)

@fine0830 Should we add some docs to add some docs here to share how to add a new menu?

**Comment by yswdqz** [comment]
I get it.

**Comment by Fine0830** [comment]
> @Fine0830 Should we add some docs to add some docs here to share how to add a new menu?

Yes. Or we need to modify the menu frequently, we can consider using configuration to dynamically display the menu.

**Comment by wu-sheng** [comment]
We could do that when have time.

**Comment by wu-sheng** [comment]
We could maintain this as a JSON at the backend, and provide a GraphQL service. Is that working for UI?

**Comment by Fine0830** [comment]
> We could maintain this as a JSON at the backend, and provide a GraphQL service. Is that working for UI?

Yes, it works.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/issues/9506 on 9.3.0 only.

**Pull request merged**
