### PR TITLE
fix: resizing window causes the trace graph to display incorrectly

### PR DESCRIPTION
**Pull request by Fine0830**
Fixes https://github.com/apache/skywalking/issues/11809

Video

https://github.com/apache/skywalking-booster-ui/assets/20871783/c0854adc-a591-486e-a5fa-1fc1f6a7e919

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
@CzyerChen Could you check this?

**Comment by CzyerChen** [comment]
> @CzyerChen Could you check this?

ok, I'll validate this version.

**Comment by CzyerChen** [comment]
I tried by changing the initial height of svg, then the full image can displayed.
image

**Comment by Fine0830** [comment]
Please check if it is the latest code, it works on my side.

**Comment by wu-sheng** [comment]
Such as, whether the list at the left side(segment list), or some other things limit the height? Or make the vertical scrolling bar doesn't work as expected?

**Comment by Fine0830** [comment]
The bug is easy to reproduce in the `demo` env. Actually, this is not related to the data.

**Review by wu-sheng — APPROVED** [review]
Merge first, as it is reproducible.

**Comment by CzyerChen** [comment]
> @CzyerChen This fix is about resizing. What is the cause at your side?

At my side,  I see the trace-list-download svg  initial height depends on the span count and VNode count without refs count
` this.svg.attr("height", (this.row.length + fixSpansSize + 1) * this.barHeight);` 
When several refs shown in the graph, the initial height is not enough, and the graph will be incomplete.

I have checked again(the code is latest), may be the fix not matched my issue.

**Comment by Fine0830** [comment]
This PR fixes the following bug

https://github.com/apache/skywalking-booster-ui/assets/20871783/f0026f08-cd02-4546-b921-425bd5e29d7d

**Pull request merged**
