### PR TITLE
Fix bugs: active side bar

### PR DESCRIPTION
**Pull request by heyanlong**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please provide screenshots for reviewing.

**Comment by heyanlong** [comment]
image

**Comment by Fine0830** [comment]
There are some code style problems. Could you please fix them?

**Comment by wu-sheng** [comment]
> There are some code style problems. Could you please fix them?

Could you consider to add code style check in the CI? In case some missed, and people will change them from one way to another repeatedly due to different local env setup.

**Comment by Fine0830** [comment]
> > There are some code style problems. Could you please fix them?
> 
> Could you consider to add code style check in the CI? In case some missed, and people will change them from one way to another repeatedly due to different local env setup.

Uh...I will add git hooks to automatically format the uniform code style.

**Review by Fine0830 — APPROVED** [review]

**Review by Fine0830 — APPROVED** [review]

**Pull request merged**
