### PR TITLE
feat: visualize attached events on the trace widget

### PR DESCRIPTION
**Pull request by Fine0830**
Visualize attached events on the trace widget.

Video 

https://user-images.githubusercontent.com/20871783/203502893-5e59836e-541d-487c-89df-72df4039ce3b.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you share what the event detail looks like? And what does the number in the timeline mean? And is the event showing on the table view?

**Comment by Fine0830** [comment]
Updated

https://user-images.githubusercontent.com/20871783/203515831-a28ca1d2-f91c-4fda-af7e-4cfccb23866d.mov

**Comment by wu-sheng** [comment]
> > what does the number in the timeline mean?
> 
> It means 15:30:5 -- 15:30:12
> 
> 

Does this work for ms? even microsecond? 

@mrproliu From my understanding, an HTTP RPC usually takes less than 10ms, some could be 2ms-3ms even less.

**Comment by wu-sheng** [comment]
How does this example run an RPC in several seconds?

**Comment by Fine0830** [comment]
> > > what does the number in the timeline mean?
> > 
> > 
> > It means 15:30:5 -- 15:30:12
> > 
> 
> Does this work for ms? even microsecond?
> 
> @mrproliu From my understanding, an HTTP RPC usually takes less than 10ms, some could be 2ms-3ms even less.

The minimum granularity the timeline supports is milliseconds.

**Comment by Fine0830** [comment]
The timeline granularity is changed by scaling. It does not support microseconds.

**Comment by mrproliu** [comment]
The demo of the attached event using real data? The start/end time of the event is usually smaller than 1s. 

> @mrproliu From my understanding, an HTTP RPC usually takes less than 10ms, some could be 2ms-3ms even less.

Less than 10ms maybe too few. Usually is less than 100ms. Here is what real data seem like(through CLI):
image

**Comment by Fine0830** [comment]
> The demo of the attached event using real data? The start/end time of the event is usually smaller than 1s.
> 

No, it is mock data.

**Comment by Fine0830** [comment]
> The demo of the attached event using real data? The start/end time of the event is usually smaller than 1s.
> 
> > @mrproliu From my understanding, an HTTP RPC usually takes less than 10ms, some could be 2ms-3ms even less.
> 
> Less than 10ms maybe too few. Usually is less than 100ms. Here is what real data seem like(through CLI): image

Visualize the screenshot attached events

https://user-images.githubusercontent.com/20871783/203554025-eeea47ad-1159-4dae-a316-60398aa1df19.mov

**Comment by wu-sheng** [comment]
What is the initialized width of the time window? Is this based on span's duration?

**Comment by Fine0830** [comment]
Initial state of the timeline

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
