### PR TITLE
Add gateway,apisix menu

### PR DESCRIPTION
**Pull request by pg-yang**
related issue  https://github.com/apache/skywalking/issues/9677
I  couldn't find appropriate icon for level one menu `Gateway` , Any suggestion ?  

image

image

### CODE REVIEW

**Comment by wu-sheng** [comment]
@Fine0830 Could you add an icon for this new menu(Gateway)?

**Comment by Fine0830** [comment]
> @Fine0830 Could you add an icon for this new menu(Gateway)?

No problem.

**Comment by Fine0830** [comment]
Screenshot

**Review by Fine0830 — APPROVED** [review]

**Comment by wu-sheng** [comment]
Good to me.

**Pull request merged**
