### PR TITLE
fix: update query conditions for the browser logs

### PR DESCRIPTION
**Pull request by Fine0830**
Fixes query conditions for the browser logs. Reference https://github.com/apache/skywalking/discussions/9208

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
According to https://github.com/apache/skywalking-query-protocol/blob/master/browser-log.graphqls, it seems no tag as a condition, instead, we should add a catalog condition.

This part should be removed.
image

**Comment by Fine0830** [comment]
Done

**Comment by wu-sheng** [comment]
Take a look at `Catalog` (https://github.com/apache/skywalking-query-protocol/blob/master/browser-log.graphqls#L23)

**Comment by Fine0830** [comment]
Have Updated `Alarm` to `Alerting` and added a catalog selector in the log header.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
