### PR TITLE
feat: supporting expressions to query metrics data

### PR DESCRIPTION
**Pull request by Fine0830**
Videos / Screenshots

https://github.com/apache/skywalking-booster-ui/assets/20871783/e41eda74-0ba4-410d-a489-573a9ef44f46

https://github.com/apache/skywalking-booster-ui/assets/20871783/be275d3f-7ecb-4026-88a2-03ede7232b57

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Let's support summary exp and detail exp for table widget. 
Permanently remove calculation features from the expression option.
We are deprecating this from the main stream since 9.5.0. Thanks.

**Comment by Fine0830** [comment]
> Let's support summary exp and detail exp for table widget. Permanently remove calculation features from the expression option. We are deprecating this from the main stream since 9.5.0. Thanks.

Done

**Comment by wu-sheng** [comment]
image

Could you make these two in one line to indicate these are for one column? Then put a title for two. The first should be required, the second is optional.

And, did you miss the place to set up the title of this column? How about a title setup and two expressions are in the same line? Or in one block?

**Comment by wu-sheng** [comment]
Another question is, it looks like both General and expression are working at the same time, how to determine the order of  left to right?

**Comment by Fine0830** [comment]
Updated

https://github.com/apache/skywalking-booster-ui/assets/20871783/8025fb36-43db-419b-a8b8-ffa68325c3a0

**Comment by wu-sheng** [comment]
Could you share how to set up column title? Is the calculation disabled?

**Comment by Fine0830** [comment]
> Could you share how to set up column title? Is the calculation disabled?

Sure.

**Comment by wu-sheng** [comment]
@wankai123 Do we still need `subscript`? I think we could format all through expression, right?

**Comment by wankai123** [comment]
> subscript

yes, we can calculate through expression.

**Comment by wu-sheng** [comment]
@Fine0830 Please remove it as well.

**Comment by Fine0830** [comment]
Done

**Review by wu-sheng — APPROVED** [review]
Good to me. @wankai123 could test and sync.

**Pull request merged**
