### PR TITLE
Feat: Alert channels

### PR DESCRIPTION
**Pull request by heyanlong**
image
image
image
image

### CODE REVIEW

**Comment by wu-sheng** [comment]
I don't think the backend supports this.

**Comment by wu-sheng** [comment]
Including https://github.com/apache/skywalking-booster-ui/pull/4. @Fine0830 

I think both of them are not supported in backend, as generally, SkyWalking don't provide management features. All alarm settings should be set through dynamic configuration service or dynamic config servers.

**Comment by wu-sheng** [comment]
From v8 to v9, we are adding new dashboard and new perspective(layer) for UI, but we don't agree with making SkyWalking to cover management fields. 
Mostly because if we do, many others things, like login, data access control, visible scope, will be added. The whole PMC don't have any discussion or conclusion about it. According to old vote, even `login` can't be approved(years back)

**Comment by heyanlong** [comment]
This feature appears in the prototype design.

**Comment by wu-sheng** [comment]
Prototype is prototype. But until you have OAP server supports, this UI only causes confusion if we includes it.
I don't mean these 2 features are wrong, or design is wrong. The key point is we need to take the feature step by step.

**Comment by heyanlong** [comment]
Okay, I'll complete the feature of OAP already has.

**Pull request closed without merging**
