### PR TITLE
feat: update trace profiling protocol

### PR DESCRIPTION
**Pull request by Fine0830**
Reference https://github.com/apache/skywalking-query-protocol/pull/111

Video 

https://user-images.githubusercontent.com/20871783/228215542-f849c779-001e-4601-adc5-1317ebd11d53.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by mrproliu** [comment]
Could you provide an image when the span cannot be profiled? 
We do not have a multi-segment situation in the current demo environment.

**Comment by wu-sheng** [comment]
Besides the un-profilied span, @mrproliu do we have mock data about the cross-thread profiling? I think we need to check whether the segments are linked and whether the stack is able to support this case.

**Comment by mrproliu** [comment]
For now, I just check it locally. Tomorrow, I will change the "songs" service to use Undertow as Web Service in the test environment, then let @Fine0830 try it out.

**Comment by Fine0830** [comment]
What is the condition of un-profiled span? @mrproliu

**Comment by wu-sheng** [comment]
> For now, I just check it locally. Tomorrow, I will change the "songs" service to use Undertow as Web Service in the test environment, then let @Fine0830 try it out.

Make sense. FYI @kezhenxu94 To adopt the new profiling feature, we are going to make the `songs` service somehow has x-thread tasks in the workflow.

**Comment by mrproliu** [comment]
> What is the condition of un-profiled span? @mrproliu

https://github.com/apache/skywalking-query-protocol/blob/master/profile.graphqls#L137 as `false`

**Comment by Fine0830** [comment]
I don't found the mock data about un-profiled span. Can you provide this? @mrproliu

**Comment by Fine0830** [comment]
Add a tip for un-profiled spans.

https://user-images.githubusercontent.com/20871783/228427875-5cbc3f07-2e25-4e23-94ea-88bf6631777d.mov

**Comment by wu-sheng** [comment]
@mrproliu Is `undertow` the un-profilied span? I thought we have it profiled.

**Comment by mrproliu** [comment]
> @mrproliu Is undertow the un-profilied span? I thought we have it profiled.

The "/songs" is un-profiled span. The real code is running on the "UndertowDispatch".

**Comment by Fine0830** [comment]
Are there any further questions? @mrproliu @wu-sheng

**Comment by wu-sheng** [comment]
I had a discussion with @mrproliu. He will forward the conclusion to you soon, I think. :)
There are some polish requirements at here and trace page.

**Comment by Fine0830** [comment]
Done

https://user-images.githubusercontent.com/20871783/228523237-21675cb5-31b8-4c73-a333-a4825b30b720.mov

**Comment by wu-sheng** [comment]
Let's add the icons to the `List` view of the trace too. It should be helpful

**Comment by Fine0830** [comment]
> Let's add the icons to the `List` view of the trace too. It should be helpful

Done

**Comment by Fine0830** [comment]
Add tips

https://user-images.githubusercontent.com/20871783/228706205-81c77fe2-16ce-45d3-ad94-a69e3a1d77f1.mov

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
