### PR TITLE
feat: add the MYSQL layer and update layer routers

### PR DESCRIPTION
**Pull request by Fine0830**
According to https://github.com/apache/skywalking/pull/9432#issuecomment-1207200016, update layers and routers.

Video 

https://user-images.githubusercontent.com/20871783/183278712-fe12d017-872e-446c-8269-970fcab1a30c.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
The top-level menu Databases should be kept. The sub-menu in the general service should be `Virtual Database. And MySQL should be the sub-menu of `Database`

**Comment by wu-sheng** [comment]
@yswdqz After this is merged and synced in the main repo, you could set your dashboard as root, and open from the menu directly.

**Comment by wu-sheng** [comment]
Could you post the latest screenshot?

**Comment by Fine0830** [comment]
> Could you post the latest screenshot?

Sure. Waiting for the demo env to recover.

**Comment by Fine0830** [comment]
> Could you post the latest screenshot?

Please recheck

https://user-images.githubusercontent.com/20871783/183283739-a9e216a9-ad50-4571-93fe-d903d5f7228f.mov

**Review by wu-sheng — APPROVED** [review]
We need a sync for this.

**Pull request merged**
