### PR TITLE
feat: Implement the Event widget

### PR DESCRIPTION
**Pull request by Fine0830**
Closes https://github.com/apache/skywalking/issues/9126

Video/Screenshot

https://user-images.githubusercontent.com/20871783/174768468-7850d79b-b4c1-4f95-8a9e-bac7904cf954.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is this widget on the instance only? Or instance and service? I think the endpoint level makes little sense.

@kezhenxu94 What do you think?

**Comment by wu-sheng** [comment]
@kezhenxu94 I think this widget should be on the top of the tags?

@Fine0830 Is the height of each event could be flexible? Like the chrome browser doing? I think the event's number is not very predictable.
Another question is, is there a total limitation for events? To avoiding crashing the visualization or the page?

**Comment by Fine0830** [comment]
> @kezhenxu94 I think this widget should be on the top of the tags?
> 
> @Fine0830 Is the height of each event could be flexible? Like the chrome browser doing?

Yes, it is. 

https://user-images.githubusercontent.com/20871783/174778233-c430c25d-60d1-45c3-b74f-5918272798a5.mov

**Comment by wu-sheng** [comment]
I mean each bar. Such as set the whole widget as 20, is every event bar in height 4 if five events found, and in height 1 when 20 events(max per page)

**Comment by Fine0830** [comment]
> Is this widget on the instance only? Or instance and service? I think the endpoint level makes little sense.
> 
> @kezhenxu94 What do you think?

Currently, when the entity type of dashboard is Service, Instance, Endpoint, here can use the Event widget. I am fine to update the widget entity limit, if you all think so.

**Comment by Fine0830** [comment]
> I mean each bar. Such as set the whole widget as 20, is every event bar in height 4 if five events found, and in height 1 when 20 events(max per page)

The `timeline` can be move by mouse.

https://user-images.githubusercontent.com/20871783/174783594-eb1e7ed8-f9e2-4aab-967a-0ff3d57e9638.mov

**Comment by wu-sheng** [comment]
OK, let's make them shorter, half of now? In my mind, we prefer to add this on the top of suitable dashboard. So, we wouldn't set this widget too high like this demo shows.

**Comment by Fine0830** [comment]
> And could we make this component folded? Is that possible?(consider how to layout in folded and unfolded)

Let me try this.

**Comment by Fine0830** [comment]
Latest screenshot

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
