### PR TITLE
feat: Implement independent mode for widgets

### PR DESCRIPTION
**Pull request by Fine0830**
Closes https://github.com/apache/skywalking/issues/10152

Videos

https://user-images.githubusercontent.com/20871783/216510982-66c3d51a-509e-4438-b74c-aff886411b4a.mov

https://user-images.githubusercontent.com/20871783/216510997-7706862e-2f5b-42c4-bf7f-7558565bd270.mov

https://user-images.githubusercontent.com/20871783/216511008-e2e32483-9cd9-488e-bd6a-aaeafb8c6187.mov

https://user-images.githubusercontent.com/20871783/216511024-86a8b1c6-e296-40c5-928e-d338d46afc71.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by Fine0830** [comment]
@wu-sheng Please review

**Comment by wu-sheng** [comment]
Two questions
1. Whether the URL would be too long? Does the user have to use POST?
2. In this mode, I think menu should be not available.

**Comment by Fine0830** [comment]
> Two questions
> 
> 1. Whether the URL would be too long? 

This URL does not exceed the length limit of the URL set by the browser. These are the maximum values of the browser. Firefox is 65,536. Safari is 80,000. Opera is 190,000. Chrome is 8182(characters). So I think the URL is good.

> Does the user have to use POST?

It is a front-end route, so it does not affect the interaction between the ui and serve.

**Comment by wu-sheng** [comment]
> > Two questions
> > 
> > 1. Whether the URL would be too long?
> 
> This URL does not exceed the length limit of the URL set by the browser. These are the maximum values of the browser. Firefox is 65,536. Safari is 80,000. Opera is 190,000. Chrome is 8182(characters). So I think the URL is good.
> 
> > Does the user have to use POST?
> 
> It is a front-end route, so it does not affect the interaction between the ui and serve.

Got it, I think GET should be good then.

**Comment by Fine0830** [comment]
> 2. In this mode, I think the menu should be not visiable.

Done

**Comment by wu-sheng** [comment]
Could you remove all(including the black bar)? The use case is, users could build a warzone dashboard using multiple URLs with iFrames.

**Comment by Fine0830** [comment]
> Could you remove all(including the black bar)? The use case is, users could build a warzone dashboard using multiple URLs with iFrames.

Done

**Comment by wu-sheng** [comment]
One more question, are all settings included in the URL? Such as height. Could you try to use several iFrames, each one links to  one URL? 
Let's see how it looks like you build a page with these iFrames to simulate a custom dashboard.

**Comment by Fine0830** [comment]
> One more question, are all settings included in the URL? Such as height. Could you try to use several iFrames, each one links to one URL? Let's see how it looks like you build a page with these iFrames to simulate a custom dashboard.

> One more question, are all settings included in the URL? Such as height. Could you try to use several iFrames, each one links to one URL? Let's see how it looks like you build a page with these iFrames to simulate a custom dashboard.

There are only some settings in the URL, and height is here. This is a demo.

https://user-images.githubusercontent.com/20871783/216884949-f0bb1aee-633f-43e2-bc60-d12631fe537c.mov

**Comment by wu-sheng** [comment]
Is the height set when generate URL?

**Comment by Fine0830** [comment]
> Is the height set when generate URL?

Yes.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
