### PR TITLE
Add websphere icon(#10887)

### PR DESCRIPTION
**Pull request by weixiang1862**

### CODE REVIEW

**Review by Fine0830 — APPROVED** [review]

**Comment by wu-sheng** [comment]
Is this icon licensed by EPLv2 as well? Be careful about the commercial logo.

**Comment by weixiang1862** [comment]
@wu-sheng I download it from iconfont website，I will check with the author as soon as possible.

**Comment by wu-sheng** [comment]
> @wu-sheng I download it from iconfont website，I will check with the author as soon as possible.

Then it isn't. Because even the author granted to us, we can't grant to our users by following Apache 2.0 License.

**Comment by weixiang1862** [comment]
> > @wu-sheng I download it from iconfont website，I will check with the author as soon as possible.
> 
> Then it isn't. Because even the author granted to us, we can't grant to our users by following Apache 2.0 License.

I see. I will find another one.

**Comment by wu-sheng** [comment]
It is better you build one, or we could leave it as blank(default icon). I don't want any concern with Oracle Inc.

**Comment by wu-sheng** [comment]
Closing due to unclear license.

**Pull request closed without merging**
