### PR TITLE
Add AWS API Gateway menu

### PR DESCRIPTION
**Pull request by pg-yang**
Related issue https://github.com/apache/skywalking/issues/9883

image

### CODE REVIEW

**Comment by wu-sheng** [comment]
Let's rename `AWS Gateway` to `AWS API Gateway`, as this is AWS official name, https://aws.amazon.com/api-gateway/?nc1=h_ls

**Comment by wu-sheng** [comment]
In AWS menu, it could be `API Gateway`. But in `Gateway` catalog, we have to have `AWS API Gateway`.

**Comment by pg-yang** [comment]
image


`AWS API Gateway` has too many words to display completely

**Comment by wu-sheng** [comment]
@Fine0830 Any suggestion about this kind of long name?

**Review by wu-sheng — APPROVED** [review]
@pg-yang I am going to merge this first, as I don't want to this blocks you. @Fine0830 is on vacation. Let's polish this after she is back.

**Comment by Fine0830** [comment]
> @Fine0830 Any suggestion about this kind of long name?

Widen the menu, or update `AWS API Gateway` to `AWS API`?

**Comment by wu-sheng** [comment]
I feel there are still spaces at the right, but somehow it doesn't show up.

**Pull request merged**
