### PR TITLE
fix: the service parameter is wrong when the view dump from Log to Trace widget by clicking traceID

### PR DESCRIPTION
**Pull request by Fine0830**
Fixes https://github.com/apache/skywalking/discussions/9371

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by jampsen** [comment]
Hi, Thank you for your contribution. 
We tried the daily package: skywalking/ui:33e3f28fcf13683895737ea5551af5b6a16df219
And we find that When Trace page jump to Log page , The Service will still change to default.
Log jump to Trace page is fine.
image
image

**Comment by Fine0830** [comment]
> Hi, Thank you for your contribution. We tried the daily package: skywalking/ui:33e3f28fcf13683895737ea5551af5b6a16df219 And we find that When Trace page jump to Log page , The Service will still change to default. Log jump to Trace page is fine. image image

Please check your version, this bug was fixed in 9.7.0.

**Comment by Fine0830** [comment]
It works on my side.

https://github.com/apache/skywalking-booster-ui/assets/20871783/97e777ad-06e6-4528-ba3e-23c1a6a40f0a

**Comment by jampsen** [comment]
In my case, the problem only happen when Trace jump to Log page, Log jump to Trace page is also fine.

https://github.com/apache/skywalking-booster-ui/assets/35960370/989eca24-a5de-4d55-ac56-4ceeddc4a123

**Pull request merged**
