### PR TITLE
docs: update img of ActiveMQ

### PR DESCRIPTION
**Pull request by CzyerChen**
update image of ActiveMQ, size: 100*100

- source file: 
https://activemq.apache.org/assets/img/activemq_logo_white_vertical.png

- processed by free tool Adobe  Express:
https://www.adobe.com/cn/express/feature/image/resize/jpg
https://www.adobe.com/cn/express/feature/image/remove-background

### CODE REVIEW

**Comment by wu-sheng** [comment]
Do you have the screenshot of the new image in the topology?

**Comment by CzyerChen** [comment]
> Do you have the screenshot of the new image in the topology?

OK, I will give it later.

**Comment by CzyerChen** [comment]
> Do you have the screenshot of the new image in the topology?

image

**Comment by wu-sheng** [comment]
I can see the whitespace in the logo, rather than transparent. Is it possible to change it?

**Comment by CzyerChen** [comment]
> transparent

image

**Comment by wu-sheng** [comment]
Yes, is this improving the view of topology?

**Comment by CzyerChen** [comment]
> Yes, is this improving the view of topology?

OK.

**Comment by CzyerChen** [comment]
about logo:
image

in topology: 
image

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
