### PR TITLE
feat: implement dashboard layouts

### PR DESCRIPTION
**Pull request by Fine0830**
The PR implements the dashboard layout for creating and editing dashboards. The layout is draggable and resizable grids.  I would like to make a new page(popup) implement the Configuration UI for dashboard, but it is less conducive to what you see is what you get. So I implement another way, as you can see from the following video the scroll bar in the middle affects the attractiveness of the page. I think it's not good. WDYT. Please free feel to comment if you have any question and issue. Feedback will be appreciated.  

Screenshots(video)

https://user-images.githubusercontent.com/20871783/147308445-ec613767-6a5a-41b7-9815-0301f9c56075.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you post a record video about how this works here? (Before merging)

**Comment by Fine0830** [comment]
> Could you post a record video about how this works here? (Before merging)

Sure.

**Comment by wu-sheng** [comment]
What do service and service instance mean? I think dashboard should set whether have instance tab, rather than a specific service?

**Comment by Fine0830** [comment]
> What do service and service instance mean? I think dashboard should set whether have instance tab, rather than a specific service?
> 
> Don't need to lock service or service instance. WDYT?

Probably the video can more clearly show the interaction of the page. Here uses a cascade selector with services and service  instances(endpoints) instead that Rocketbot UI use two selectors for services and service  instances(endpoints).

https://user-images.githubusercontent.com/20871783/147356958-2bb040ed-ccc9-4399-924c-8f240668da7e.mov

**Comment by wu-sheng** [comment]
I think I got the idea correctly. My suggestion is, the v9 standard layout is always 
1. Service list as private page.
2. Click service could have service level metrics panel
3. Instance Level provide instance list, then dive into instance metrics panel
4. Endpoint is similar with (3)

(3) and (4) are both optional, and could customize name(such as name instance panel as `pods panel`). The creating/setup page could choose (3) and (4) activated or not.

**Review by heyanlong — APPROVED** [review]

**Comment by Fine0830** [comment]
Please recheck


https://user-images.githubusercontent.com/20871783/147450111-d9a84f9a-2952-4c24-b8c6-dbe1127384cd.mov

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
