### PR TITLE
refactor: update Logs view

### PR DESCRIPTION
**Pull request by Fine0830**
Video 

https://github.com/apache/skywalking-booster-ui/assets/20871783/b4ef21c6-4391-4d5e-a44b-03c0cb4808e2

Singed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you provide a preview how a longer log looks like?

**Comment by Fine0830** [comment]
> Could you provide a preview how a longer log looks like?

**Comment by wu-sheng** [comment]
Could you lock the column width and make the content into multiple rows?

**Comment by wu-sheng** [comment]
And only the value of tag=level should be shown as Level column.

**Comment by Fine0830** [comment]
Updated

**Comment by wu-sheng** [comment]
Let's remove trace ID text, but only a link named trace. Then more spaces for the log raw text.

**Comment by Fine0830** [comment]
Do we need the `Service` column, as the values are always the same?

**Comment by wu-sheng** [comment]
We don't support all services, right? 
If so, feel free to remove it too.

**Comment by Fine0830** [comment]
> We don't support all services, right? If so, feel free to remove it too.

Right

**Comment by Fine0830** [comment]
Changed

**Pull request merged**
