### PR TITLE
feat: enhance associating metrics with traces by `refId`

### PR DESCRIPTION
**Pull request by Fine0830**
Enhance associating metrics with traces by `refId`.

Video 

https://user-images.githubusercontent.com/20871783/203776288-7c47275a-c94a-4a50-bf20-f4f8a59eb489.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
BTW, could you add a setting(default yes) to indicate this `Theref-id is a trace ID`? Because one day, we may link sampled record to log ID.

**Comment by Fine0830** [comment]
> BTW, could you add a setting(default yes) to indicate this `Theref-id is a trace ID`? Because one day, we may link sampled record to log ID.

What do you think of this?

**Comment by Fine0830** [comment]
@mrproliu  Attached event details

**Comment by wu-sheng** [comment]
I mean in the widget setup for SampledRecord.

**Comment by Fine0830** [comment]
> I mean in the widget setup for SampledRecord. Only dashboard setup open this option, you would use the refId as trace ID and show the menu item.

I'm a bit confused. Can the `refId`(https://github.com/apache/skywalking-query-protocol/blob/master/record.graphqls#L46) be a traceId or logId?

**Comment by wu-sheng** [comment]
For now, it is only trace ID. That is why I am asking for this option to be opened by default when you add it.
But, I have a feeling, we would have log ID sampled as well in the future.

**Comment by Fine0830** [comment]
What do you think of this? @wu-sheng 

https://user-images.githubusercontent.com/20871783/203942880-cb30545b-17ac-487b-941a-58b3f747269f.mov

**Comment by wu-sheng** [comment]
One little more, could we provide a `None` option? If the ID exists but not a Trace ID somehow.

**Comment by Fine0830** [comment]
> One little more, could we provide a `None` option? If the ID exists but not a Trace ID somehow.

Done

https://user-images.githubusercontent.com/20871783/203945212-89cd78b3-98b8-436a-a128-bdad88530e29.mov

**Review by wu-sheng — APPROVED** [review]
BTW, please check the main repo changelog. I remember yesterday, @wankai123 's sync seems not updating it, I am not sure whether there are some things required to be added.

**Pull request merged**
