### PR TITLE
(Summer 2022)Add nanoToMill tool(WIP)

### PR DESCRIPTION
**Pull request by easonyipj**
# Backgroud
The go2sky add a [new feature](https://github.com/SkyAPM/go2sky/pull/168) to collcect golang runtime metrics,
and the gc time's unit is nanosecond, but it's more appropriate to show in millseconds, so there need a nanoToMill function in ui codes

# Feature
Add a new calculations that tranfer nanosecond to millseconds
`case Calculations.NanoToMill:
      data = (val / 1000000).toFixed(4);
      break;`

### CODE REVIEW

**Comment by wu-sheng** [comment]
image

I can see this on the UI, what do I miss?

**Review by Fine0830 — COMMENTED** [review]
You should add the new option to `CalculationOpts` in `src/views/dashboard/data.ts`. @easonyipj

**Comment by wu-sheng** [comment]
@Fine0830 Why do I see this formula already?

**Comment by Fine0830** [comment]
> @Fine0830 Why do I see this formula already?

The `NanosecondToMillisecond` should be newly added before for process dashboards.

**Comment by easonyipj** [comment]
> > @Fine0830 Why do I see this formula already?
> 
> The `NanosecondToMillisecond` should be newly added before for process dashboards.

Yes, it's my fault to ignore the newly functions, I will close the pr, thanks for you all

**Comment by easonyipj** [comment]
> @Fine0830 Why do I see this formula already?

Yes, it's my fault to ignore the newly functions, I will close the mr, thanks for you all

**Pull request closed without merging**
