### PR TITLE
feat: Add Aerospike icon for Java plugin (#10992)

### PR DESCRIPTION
**Pull request by dd1k**
Related issue https://github.com/apache/skywalking/issues/10992

image

### CODE REVIEW

**Review by Fine0830 — APPROVED** [review]

**Comment by wu-sheng** [comment]
I think it is. Found this on their website, Aerospike, Inc. This logo belongs to a vendor. We are not granted to use.

**Comment by dd1k** [comment]
> I think it is. Found this on their website, Aerospike, Inc. This logo belongs to a vendor. We are not granted to use.

I'll go confirm.

**Comment by wu-sheng** [comment]
No logo is fine, it would block your PR. The runtime codes has GPL license, which is good enough.

**Comment by dd1k** [comment]
ok!

**Pull request closed without merging**
