### PR TITLE
refactor: optimize the attached events visualization in the trace widget

### PR DESCRIPTION
**Pull request by Fine0830**
Optimize the attached events visualization in the trace widget.

Video 

https://user-images.githubusercontent.com/20871783/218926782-2a6e314d-2429-4f2d-85a3-42e5c64eead2.mov

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by mrproliu** [comment]
The events look like not ordering. These should be sorted by ascending.

**Comment by Fine0830** [comment]
> The events look like not ordering? These should be sorted by ascending.

Sort data by event duration. Do you mean to sort data by "startTime"?

**Comment by mrproliu** [comment]
> Sort data by event duration. Do you mean to sort data by "startTime"?

Yes. It should be sort by start time.

**Comment by Fine0830** [comment]
Done

**Review by mrproliu — APPROVED** [review]
LGTM.

**Pull request merged**
