### PR TITLE
feat: improve dashboard queries to make  page opening brisker

### PR DESCRIPTION
**Pull request by Fine0830**
Closes https://github.com/apache/skywalking/issues/12416

Video

https://github.com/user-attachments/assets/2d808e59-8bc8-40f2-8f15-0a27e45fbb75

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you add comments about which queries are going to be merged? Which would not?

And how to separate the sub queries in different request? I assume we can't put all of them in one request

**Comment by Fine0830** [comment]
> Could you add comments about which queries are going to be merged? Which would not?
> 
> And how to separate the sub queries in different request? I assume we can't put all of them in one request

Sure. Divide all the widgets on the current page into multiple arrays of length 6, and merge the metric queries of the 6 widgets into one query, excluding the service/instance/endpoint list. The service/instance/endpoint list component is treated as a separate query.

**Comment by wu-sheng** [comment]
Then how about trace query and log query?

**Comment by Fine0830** [comment]
It contains metric widgets, but does not include trace, log, and other widgets.

**Review by wu-sheng — APPROVED** [review]
Let's sync this to the main repo.

**Pull request merged**
